@isTest
private class TestClasses {
	/*
    static testMethod void ChangeOwnerId() { 
      
      User_Status__c userStatus1 = new User_Status__c(OwnerId = [select Id from User WHERE IsActive = true limit 1].Id, Status__c = 'Out of Office');      
      Account acc = new Account(Name='Test Account', Phone = '0987654321');
      insert acc;
      
      Lead newLead4 = new Lead(FirstName= 'Test',LastName = 'Test3', Status = 'Open', Company = 'Test3', Phone='9412365', Email='amit.luniya1@arxxus.com', TrackTrigger__c=1, LeadSource = 'Web', OwnerId = userStatus1.OwnerId);
      insert newLead4;
       
      acc.OwnerId = userStatus1.OwnerId;
      update acc;
      
      Lead newLead3 = new Lead(FirstName= 'Test',LastName = 'Test3', Status = 'Open', Company = 'Test3', Phone='3456815354', Email='amit.luniya2@arxxus.com', TrackTrigger__c=1, LeadSource = 'Web', OwnerId = userStatus1.OwnerId);
      insert newLead3; 
      
        //Lead newLead4 = new Lead(FirstName= 'Test',LastName = 'Test3', Status = 'Open', Company = 'Test3', Phone='123', Email='amit.luniya@arxxus.com');
      //insert newLead4;         
    }
    
    static testMethod void ChangeOwnerIdNew() {
        Lead newLead6 = new Lead(FirstName= 'Test',LastName = 'Test6', Status = 'Open', Company = 'Test6', Email='amit3@gmail.com', TrackTrigger__c=1, OwnerId = '00530000004W020', LeadSource = 'Web');
      insert newLead6;             
    }
    static testMethod void ChangeOwnerId1() {    
      Lead newLead5 = new Lead(FirstName= 'Test',LastName = 'Test5', Status = 'Open', Company = 'Test5', Phone='345326800' , TrackTrigger__c=1, OwnerId = '00530000004W020', Email='amit4@gmail.com', LeadSource = 'Web');
      insert newLead5;
    }
    static testMethod void ChangeOwnerIdNew1() {
      Lead newLead1 = new Lead(FirstName= 'Test',LastName = 'Test1', Status = 'Open', Company = 'Test1', Email = 'amit.luniya5@arxxus.com', Phone='11394875623', OwnerId = '00530000004W020', TrackTrigger__c=1 , LeadSource = 'Web');
      insert newLead1;
        
    }
    */
}