/**
 * TestDataFactoryTests
 * Author: Steve O'Neal
 * Purpose: Tests the creation of generic SObjects for use in test classes
 * Ticket: BAP-3444
 *
 * Updates:
 * *********
 * 
 */
@isTest
private class TestDataFactoryTest {
	
	/**
	 * Increases code coverage until a better solution can be found
	 * @author Steve O'Neal
	 * @date   2016-06-07
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3444
	 * @return nothing
	 */
	static testMethod void test_method_one() {
		TestDataFactory.IncreaseCodeCoverage();
	}
	
}